
export  const  regionMap = [
    {region:'北京', key:'京'},
    {region:'天津', key:'津'},
    {region:'河北', key:'冀'},
    {region:'山西', key:'晋'},
    {region:'内蒙古', key:'内蒙古'},
    {region:'辽宁', key:'辽'},
    {region:'吉林', key:'吉'},
    {region:'黑龙江', key:'黑'},
    {region:'上海', key:'沪'},
    {region:'江苏', key:'苏'},
    {region:'浙江', key:'浙'},
    {region:'安徽', key:'皖'},
    {region:'福建', key:'闽'},
    {region:'江西', key:'赣'},
    {region:'山东', key:'鲁'},
    {region:'河南', key:'豫'},
    {region:'湖北', key:'鄂'},
    {region:'湖南', key:'湘'},
    {region:'广东', key:'粤'},
    {region:'广西', key:'桂'},
    {region:'海南', key:'琼'},
    {region:'四川', key:'川'},
    {region:'贵州', key:'贵'},
    {region:'云南', key:'云'},
    {region:'重庆', key:'渝'},
    {region:'西藏', key:'藏'},
    {region:'陕西', key:'陕'},
    {region:'甘肃', key:'甘'},
    {region:'青海', key:'青'},
    {region:'宁夏', key:'宁'},
    {region:'新疆', key:'新'},
    {region:'香港', key:'港'},
    {region:'澳门', key:'澳'},
    {region:'台湾', key:'台'},
]